#ifndef _VTSS_OCELOT_REGS_SYS_H_
#define _VTSS_OCELOT_REGS_SYS_H_

/*
 *
 * VCore-III Register Definitions
 *
 * Copyright (C) 2015 Vitesse Semiconductor Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#include "vtss_ocelot_regs_common.h"

#define VTSS_SYS_SYSTEM_RESET_CFG            VTSS_IOREG(VTSS_TO_SYS,0x142)
#define  VTSS_F_SYS_SYSTEM_RESET_CFG_CORE_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),2,1)
#define  VTSS_M_SYS_SYSTEM_RESET_CFG_CORE_ENA  BIT(2)
#define  VTSS_X_SYS_SYSTEM_RESET_CFG_CORE_ENA(x)  VTSS_EXTRACT_BITFIELD(x,2,1)
#define  VTSS_F_SYS_SYSTEM_RESET_CFG_MEM_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_SYS_SYSTEM_RESET_CFG_MEM_ENA  BIT(1)
#define  VTSS_X_SYS_SYSTEM_RESET_CFG_MEM_ENA(x)  VTSS_EXTRACT_BITFIELD(x,1,1)
#define  VTSS_F_SYS_SYSTEM_RESET_CFG_MEM_INIT(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_SYSTEM_RESET_CFG_MEM_INIT  BIT(0)
#define  VTSS_X_SYS_SYSTEM_RESET_CFG_MEM_INIT(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_SYSTEM_CMID                 VTSS_IOREG(VTSS_TO_SYS,0x143)
#define  VTSS_F_SYS_SYSTEM_CMID_CMID(x)       VTSS_ENCODE_BITFIELD(x,0,8)
#define  VTSS_M_SYS_SYSTEM_CMID_CMID          VTSS_ENCODE_BITMASK(0,8)
#define  VTSS_X_SYS_SYSTEM_CMID_CMID(x)       VTSS_EXTRACT_BITFIELD(x,0,8)

#define VTSS_SYS_SYSTEM_VLAN_ETYPE_CFG       VTSS_IOREG(VTSS_TO_SYS,0x144)
#define  VTSS_F_SYS_SYSTEM_VLAN_ETYPE_CFG_VLAN_S_TAG_ETYPE_VAL(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_SYS_SYSTEM_VLAN_ETYPE_CFG_VLAN_S_TAG_ETYPE_VAL     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_SYS_SYSTEM_VLAN_ETYPE_CFG_VLAN_S_TAG_ETYPE_VAL(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_SYS_SYSTEM_PORT_MODE(ri)        VTSS_IOREG(VTSS_TO_SYS,0x145 + (ri))
#define  VTSS_F_SYS_SYSTEM_PORT_MODE_DATA_WO_TS(x)  VTSS_ENCODE_BITFIELD(x,5,2)
#define  VTSS_M_SYS_SYSTEM_PORT_MODE_DATA_WO_TS     VTSS_ENCODE_BITMASK(5,2)
#define  VTSS_X_SYS_SYSTEM_PORT_MODE_DATA_WO_TS(x)  VTSS_EXTRACT_BITFIELD(x,5,2)
#define  VTSS_F_SYS_SYSTEM_PORT_MODE_INCL_INJ_HDR(x)  VTSS_ENCODE_BITFIELD(x,3,2)
#define  VTSS_M_SYS_SYSTEM_PORT_MODE_INCL_INJ_HDR     VTSS_ENCODE_BITMASK(3,2)
#define  VTSS_X_SYS_SYSTEM_PORT_MODE_INCL_INJ_HDR(x)  VTSS_EXTRACT_BITFIELD(x,3,2)
#define  VTSS_F_SYS_SYSTEM_PORT_MODE_INCL_XTR_HDR(x)  VTSS_ENCODE_BITFIELD(x,1,2)
#define  VTSS_M_SYS_SYSTEM_PORT_MODE_INCL_XTR_HDR     VTSS_ENCODE_BITMASK(1,2)
#define  VTSS_X_SYS_SYSTEM_PORT_MODE_INCL_XTR_HDR(x)  VTSS_EXTRACT_BITFIELD(x,1,2)
#define  VTSS_F_SYS_SYSTEM_PORT_MODE_INJ_HDR_ERR(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_SYSTEM_PORT_MODE_INJ_HDR_ERR  BIT(0)
#define  VTSS_X_SYS_SYSTEM_PORT_MODE_INJ_HDR_ERR(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_SYSTEM_FRONT_PORT_MODE(ri)  VTSS_IOREG(VTSS_TO_SYS,0x152 + (ri))
#define  VTSS_F_SYS_SYSTEM_FRONT_PORT_MODE_HDX_MODE(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_SYSTEM_FRONT_PORT_MODE_HDX_MODE  BIT(0)
#define  VTSS_X_SYS_SYSTEM_FRONT_PORT_MODE_HDX_MODE(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_SYSTEM_FRM_AGING            VTSS_IOREG(VTSS_TO_SYS,0x15d)
#define  VTSS_F_SYS_SYSTEM_FRM_AGING_AGE_TX_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),20,1)
#define  VTSS_M_SYS_SYSTEM_FRM_AGING_AGE_TX_ENA  BIT(20)
#define  VTSS_X_SYS_SYSTEM_FRM_AGING_AGE_TX_ENA(x)  VTSS_EXTRACT_BITFIELD(x,20,1)
#define  VTSS_F_SYS_SYSTEM_FRM_AGING_MAX_AGE(x)  VTSS_ENCODE_BITFIELD(x,0,20)
#define  VTSS_M_SYS_SYSTEM_FRM_AGING_MAX_AGE     VTSS_ENCODE_BITMASK(0,20)
#define  VTSS_X_SYS_SYSTEM_FRM_AGING_MAX_AGE(x)  VTSS_EXTRACT_BITFIELD(x,0,20)

#define VTSS_SYS_SYSTEM_STAT_CFG             VTSS_IOREG(VTSS_TO_SYS,0x15e)
#define  VTSS_F_SYS_SYSTEM_STAT_CFG_STAT_CLEAR_SHOT(x)  VTSS_ENCODE_BITFIELD(x,10,5)
#define  VTSS_M_SYS_SYSTEM_STAT_CFG_STAT_CLEAR_SHOT     VTSS_ENCODE_BITMASK(10,5)
#define  VTSS_X_SYS_SYSTEM_STAT_CFG_STAT_CLEAR_SHOT(x)  VTSS_EXTRACT_BITFIELD(x,10,5)
#define  VTSS_F_SYS_SYSTEM_STAT_CFG_STAT_VIEW(x)  VTSS_ENCODE_BITFIELD(x,0,10)
#define  VTSS_M_SYS_SYSTEM_STAT_CFG_STAT_VIEW     VTSS_ENCODE_BITMASK(0,10)
#define  VTSS_X_SYS_SYSTEM_STAT_CFG_STAT_VIEW(x)  VTSS_EXTRACT_BITFIELD(x,0,10)

#define VTSS_SYS_SYSTEM_SW_STATUS(ri)        VTSS_IOREG(VTSS_TO_SYS,0x15f + (ri))
#define  VTSS_F_SYS_SYSTEM_SW_STATUS_PORT_RX_PAUSED(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_SYSTEM_SW_STATUS_PORT_RX_PAUSED  BIT(0)
#define  VTSS_X_SYS_SYSTEM_SW_STATUS_PORT_RX_PAUSED(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_SYSTEM_MISC_CFG             VTSS_IOREG(VTSS_TO_SYS,0x16b)
#define  VTSS_F_SYS_SYSTEM_MISC_CFG_PTP_RSRV_CLR(x)  VTSS_ENCODE_BITFIELD(!!(x),1,1)
#define  VTSS_M_SYS_SYSTEM_MISC_CFG_PTP_RSRV_CLR  BIT(1)
#define  VTSS_X_SYS_SYSTEM_MISC_CFG_PTP_RSRV_CLR(x)  VTSS_EXTRACT_BITFIELD(x,1,1)
#define  VTSS_F_SYS_SYSTEM_MISC_CFG_PTP_DIS_NEG_RO(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_SYSTEM_MISC_CFG_PTP_DIS_NEG_RO  BIT(0)
#define  VTSS_X_SYS_SYSTEM_MISC_CFG_PTP_DIS_NEG_RO(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_SYSTEM_REW_MAC_HIGH_CFG(ri)  VTSS_IOREG(VTSS_TO_SYS,0x16c + (ri))
#define  VTSS_F_SYS_SYSTEM_REW_MAC_HIGH_CFG_REW_MAC_HIGH(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_SYS_SYSTEM_REW_MAC_HIGH_CFG_REW_MAC_HIGH     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_SYS_SYSTEM_REW_MAC_HIGH_CFG_REW_MAC_HIGH(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_SYS_SYSTEM_REW_MAC_LOW_CFG(ri)  VTSS_IOREG(VTSS_TO_SYS,0x177 + (ri))
#define  VTSS_F_SYS_SYSTEM_REW_MAC_LOW_CFG_REW_MAC_LOW(x)  (x)
#define  VTSS_M_SYS_SYSTEM_REW_MAC_LOW_CFG_REW_MAC_LOW     0xffffffff
#define  VTSS_X_SYS_SYSTEM_REW_MAC_LOW_CFG_REW_MAC_LOW(x)  (x)

#define VTSS_SYS_COREMEM_CM_ADDR             VTSS_IOREG(VTSS_TO_SYS,0x140)
#define  VTSS_F_SYS_COREMEM_CM_ADDR_CM_ADDR(x)  VTSS_ENCODE_BITFIELD(x,0,22)
#define  VTSS_M_SYS_COREMEM_CM_ADDR_CM_ADDR     VTSS_ENCODE_BITMASK(0,22)
#define  VTSS_X_SYS_COREMEM_CM_ADDR_CM_ADDR(x)  VTSS_EXTRACT_BITFIELD(x,0,22)

#define VTSS_SYS_COREMEM_CM_DATA             VTSS_IOREG(VTSS_TO_SYS,0x141)
#define  VTSS_F_SYS_COREMEM_CM_DATA_CM_DATA(x)  (x)
#define  VTSS_M_SYS_COREMEM_CM_DATA_CM_DATA     0xffffffff
#define  VTSS_X_SYS_COREMEM_CM_DATA_CM_DATA(x)  (x)

#define VTSS_SYS_PAUSE_CFG_PAUSE_CFG(ri)     VTSS_IOREG(VTSS_TO_SYS,0x182 + (ri))
#define  VTSS_F_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_START(x)  VTSS_ENCODE_BITFIELD(x,10,9)
#define  VTSS_M_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_START     VTSS_ENCODE_BITMASK(10,9)
#define  VTSS_X_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_START(x)  VTSS_EXTRACT_BITFIELD(x,10,9)
#define  VTSS_F_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_STOP(x)  VTSS_ENCODE_BITFIELD(x,1,9)
#define  VTSS_M_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_STOP     VTSS_ENCODE_BITMASK(1,9)
#define  VTSS_X_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_STOP(x)  VTSS_EXTRACT_BITFIELD(x,1,9)
#define  VTSS_F_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_ENA  BIT(0)
#define  VTSS_X_SYS_PAUSE_CFG_PAUSE_CFG_PAUSE_ENA(x)  VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_PAUSE_CFG_PAUSE_TOT_CFG     VTSS_IOREG(VTSS_TO_SYS,0x18e)
#define  VTSS_F_SYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_START(x)  VTSS_ENCODE_BITFIELD(x,9,9)
#define  VTSS_M_SYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_START     VTSS_ENCODE_BITMASK(9,9)
#define  VTSS_X_SYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_START(x)  VTSS_EXTRACT_BITFIELD(x,9,9)
#define  VTSS_F_SYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_STOP(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_SYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_STOP     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_SYS_PAUSE_CFG_PAUSE_TOT_CFG_PAUSE_TOT_STOP(x)  VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_SYS_PAUSE_CFG_ATOP(ri)          VTSS_IOREG(VTSS_TO_SYS,0x18f + (ri))
#define  VTSS_F_SYS_PAUSE_CFG_ATOP_ATOP(x)    VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_SYS_PAUSE_CFG_ATOP_ATOP       VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_SYS_PAUSE_CFG_ATOP_ATOP(x)    VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_SYS_PAUSE_CFG_ATOP_TOT_CFG      VTSS_IOREG(VTSS_TO_SYS,0x19b)
#define  VTSS_F_SYS_PAUSE_CFG_ATOP_TOT_CFG_ATOP_TOT(x)  VTSS_ENCODE_BITFIELD(x,0,9)
#define  VTSS_M_SYS_PAUSE_CFG_ATOP_TOT_CFG_ATOP_TOT     VTSS_ENCODE_BITMASK(0,9)
#define  VTSS_X_SYS_PAUSE_CFG_ATOP_TOT_CFG_ATOP_TOT(x)  VTSS_EXTRACT_BITFIELD(x,0,9)

#define VTSS_SYS_PAUSE_CFG_MAC_FC_CFG(ri)    VTSS_IOREG(VTSS_TO_SYS,0x19c + (ri))
#define  VTSS_F_SYS_PAUSE_CFG_MAC_FC_CFG_FC_LINK_SPEED(x)  VTSS_ENCODE_BITFIELD(x,26,2)
#define  VTSS_M_SYS_PAUSE_CFG_MAC_FC_CFG_FC_LINK_SPEED     VTSS_ENCODE_BITMASK(26,2)
#define  VTSS_X_SYS_PAUSE_CFG_MAC_FC_CFG_FC_LINK_SPEED(x)  VTSS_EXTRACT_BITFIELD(x,26,2)
#define  VTSS_F_SYS_PAUSE_CFG_MAC_FC_CFG_FC_LATENCY_CFG(x)  VTSS_ENCODE_BITFIELD(x,20,6)
#define  VTSS_M_SYS_PAUSE_CFG_MAC_FC_CFG_FC_LATENCY_CFG     VTSS_ENCODE_BITMASK(20,6)
#define  VTSS_X_SYS_PAUSE_CFG_MAC_FC_CFG_FC_LATENCY_CFG(x)  VTSS_EXTRACT_BITFIELD(x,20,6)
#define  VTSS_F_SYS_PAUSE_CFG_MAC_FC_CFG_ZERO_PAUSE_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),18,1)
#define  VTSS_M_SYS_PAUSE_CFG_MAC_FC_CFG_ZERO_PAUSE_ENA  BIT(18)
#define  VTSS_X_SYS_PAUSE_CFG_MAC_FC_CFG_ZERO_PAUSE_ENA(x)  VTSS_EXTRACT_BITFIELD(x,18,1)
#define  VTSS_F_SYS_PAUSE_CFG_MAC_FC_CFG_TX_FC_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),17,1)
#define  VTSS_M_SYS_PAUSE_CFG_MAC_FC_CFG_TX_FC_ENA  BIT(17)
#define  VTSS_X_SYS_PAUSE_CFG_MAC_FC_CFG_TX_FC_ENA(x)  VTSS_EXTRACT_BITFIELD(x,17,1)
#define  VTSS_F_SYS_PAUSE_CFG_MAC_FC_CFG_RX_FC_ENA(x)  VTSS_ENCODE_BITFIELD(!!(x),16,1)
#define  VTSS_M_SYS_PAUSE_CFG_MAC_FC_CFG_RX_FC_ENA  BIT(16)
#define  VTSS_X_SYS_PAUSE_CFG_MAC_FC_CFG_RX_FC_ENA(x)  VTSS_EXTRACT_BITFIELD(x,16,1)
#define  VTSS_F_SYS_PAUSE_CFG_MAC_FC_CFG_PAUSE_VAL_CFG(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_SYS_PAUSE_CFG_MAC_FC_CFG_PAUSE_VAL_CFG     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_SYS_PAUSE_CFG_MAC_FC_CFG_PAUSE_VAL_CFG(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_SYS_MMGT_MMGT                   VTSS_IOREG(VTSS_TO_SYS,0x1a7)
#define  VTSS_F_SYS_MMGT_MMGT_RELCNT(x)       VTSS_ENCODE_BITFIELD(x,16,16)
#define  VTSS_M_SYS_MMGT_MMGT_RELCNT          VTSS_ENCODE_BITMASK(16,16)
#define  VTSS_X_SYS_MMGT_MMGT_RELCNT(x)       VTSS_EXTRACT_BITFIELD(x,16,16)
#define  VTSS_F_SYS_MMGT_MMGT_FREECNT(x)      VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_SYS_MMGT_MMGT_FREECNT         VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_SYS_MMGT_MMGT_FREECNT(x)      VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_SYS_MMGT_MMGT_FAST              VTSS_IOREG(VTSS_TO_SYS,0x1a8)
#define  VTSS_F_SYS_MMGT_MMGT_FAST_FREEVLD(x)  VTSS_ENCODE_BITFIELD(x,4,4)
#define  VTSS_M_SYS_MMGT_MMGT_FAST_FREEVLD     VTSS_ENCODE_BITMASK(4,4)
#define  VTSS_X_SYS_MMGT_MMGT_FAST_FREEVLD(x)  VTSS_EXTRACT_BITFIELD(x,4,4)
#define  VTSS_F_SYS_MMGT_MMGT_FAST_RELVLD(x)  VTSS_ENCODE_BITFIELD(x,0,4)
#define  VTSS_M_SYS_MMGT_MMGT_FAST_RELVLD     VTSS_ENCODE_BITMASK(0,4)
#define  VTSS_X_SYS_MMGT_MMGT_FAST_RELVLD(x)  VTSS_EXTRACT_BITFIELD(x,0,4)

#define VTSS_SYS_MISC_EVENTS_DIF(ri)         VTSS_IOREG(VTSS_TO_SYS,0x1a9 + (ri))
#define  VTSS_F_SYS_MISC_EVENTS_DIF_EV_DRX(x)  VTSS_ENCODE_BITFIELD(x,6,3)
#define  VTSS_M_SYS_MISC_EVENTS_DIF_EV_DRX     VTSS_ENCODE_BITMASK(6,3)
#define  VTSS_X_SYS_MISC_EVENTS_DIF_EV_DRX(x)  VTSS_EXTRACT_BITFIELD(x,6,3)
#define  VTSS_F_SYS_MISC_EVENTS_DIF_EV_DTX(x)  VTSS_ENCODE_BITFIELD(x,0,6)
#define  VTSS_M_SYS_MISC_EVENTS_DIF_EV_DTX     VTSS_ENCODE_BITMASK(0,6)
#define  VTSS_X_SYS_MISC_EVENTS_DIF_EV_DTX(x)  VTSS_EXTRACT_BITFIELD(x,0,6)

#define VTSS_SYS_MISC_EVENTS_CORE            VTSS_IOREG(VTSS_TO_SYS,0x1ad)
#define  VTSS_F_SYS_MISC_EVENTS_CORE_EV_FWR(x)  VTSS_ENCODE_BITFIELD(!!(x),2,1)
#define  VTSS_M_SYS_MISC_EVENTS_CORE_EV_FWR   BIT(2)
#define  VTSS_X_SYS_MISC_EVENTS_CORE_EV_FWR(x)  VTSS_EXTRACT_BITFIELD(x,2,1)
#define  VTSS_F_SYS_MISC_EVENTS_CORE_EV_ANA(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_SYS_MISC_EVENTS_CORE_EV_ANA     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_SYS_MISC_EVENTS_CORE_EV_ANA(x)  VTSS_EXTRACT_BITFIELD(x,0,2)

#define VTSS_SYS_STAT_CNT(gi)                VTSS_IOREG_IX(VTSS_TO_SYS,0x0,gi,1,0,0)
#define  VTSS_F_SYS_STAT_CNT_CNT(x)           (x)
#define  VTSS_M_SYS_STAT_CNT_CNT              0xffffffff
#define  VTSS_X_SYS_STAT_CNT_CNT(x)           (x)

#define VTSS_SYS_PTP_PTP_STATUS              VTSS_IOREG(VTSS_TO_SYS,0x1ae)
#define  VTSS_F_SYS_PTP_PTP_STATUS_PTP_TXSTAMP_OAM(x)  VTSS_ENCODE_BITFIELD(!!(x),29,1)
#define  VTSS_M_SYS_PTP_PTP_STATUS_PTP_TXSTAMP_OAM  BIT(29)
#define  VTSS_X_SYS_PTP_PTP_STATUS_PTP_TXSTAMP_OAM(x)  VTSS_EXTRACT_BITFIELD(x,29,1)
#define  VTSS_F_SYS_PTP_PTP_STATUS_PTP_OVFL(x)  VTSS_ENCODE_BITFIELD(!!(x),28,1)
#define  VTSS_M_SYS_PTP_PTP_STATUS_PTP_OVFL   BIT(28)
#define  VTSS_X_SYS_PTP_PTP_STATUS_PTP_OVFL(x)  VTSS_EXTRACT_BITFIELD(x,28,1)
#define  VTSS_F_SYS_PTP_PTP_STATUS_PTP_MESS_VLD(x)  VTSS_ENCODE_BITFIELD(!!(x),27,1)
#define  VTSS_M_SYS_PTP_PTP_STATUS_PTP_MESS_VLD  BIT(27)
#define  VTSS_X_SYS_PTP_PTP_STATUS_PTP_MESS_VLD(x)  VTSS_EXTRACT_BITFIELD(x,27,1)
#define  VTSS_F_SYS_PTP_PTP_STATUS_PTP_MESS_ID(x)  VTSS_ENCODE_BITFIELD(x,21,6)
#define  VTSS_M_SYS_PTP_PTP_STATUS_PTP_MESS_ID     VTSS_ENCODE_BITMASK(21,6)
#define  VTSS_X_SYS_PTP_PTP_STATUS_PTP_MESS_ID(x)  VTSS_EXTRACT_BITFIELD(x,21,6)
#define  VTSS_F_SYS_PTP_PTP_STATUS_PTP_MESS_TXPORT(x)  VTSS_ENCODE_BITFIELD(x,16,5)
#define  VTSS_M_SYS_PTP_PTP_STATUS_PTP_MESS_TXPORT     VTSS_ENCODE_BITMASK(16,5)
#define  VTSS_X_SYS_PTP_PTP_STATUS_PTP_MESS_TXPORT(x)  VTSS_EXTRACT_BITFIELD(x,16,5)
#define  VTSS_F_SYS_PTP_PTP_STATUS_PTP_MESS_SEQ_ID(x)  VTSS_ENCODE_BITFIELD(x,0,16)
#define  VTSS_M_SYS_PTP_PTP_STATUS_PTP_MESS_SEQ_ID     VTSS_ENCODE_BITMASK(0,16)
#define  VTSS_X_SYS_PTP_PTP_STATUS_PTP_MESS_SEQ_ID(x)  VTSS_EXTRACT_BITFIELD(x,0,16)

#define VTSS_SYS_PTP_PTP_TXSTAMP             VTSS_IOREG(VTSS_TO_SYS,0x1af)
#define  VTSS_F_SYS_PTP_PTP_TXSTAMP_PTP_TXSTAMP_SEC(x)  VTSS_ENCODE_BITFIELD(!!(x),31,1)
#define  VTSS_M_SYS_PTP_PTP_TXSTAMP_PTP_TXSTAMP_SEC  BIT(31)
#define  VTSS_X_SYS_PTP_PTP_TXSTAMP_PTP_TXSTAMP_SEC(x)  VTSS_EXTRACT_BITFIELD(x,31,1)
#define  VTSS_F_SYS_PTP_PTP_TXSTAMP_PTP_TXSTAMP(x)  VTSS_ENCODE_BITFIELD(x,0,30)
#define  VTSS_M_SYS_PTP_PTP_TXSTAMP_PTP_TXSTAMP     VTSS_ENCODE_BITMASK(0,30)
#define  VTSS_X_SYS_PTP_PTP_TXSTAMP_PTP_TXSTAMP(x)  VTSS_EXTRACT_BITFIELD(x,0,30)

#define VTSS_SYS_PTP_PTP_NXT                 VTSS_IOREG(VTSS_TO_SYS,0x1b0)
#define  VTSS_F_SYS_PTP_PTP_NXT_PTP_NXT(x)    VTSS_ENCODE_BITFIELD(!!(x),0,1)
#define  VTSS_M_SYS_PTP_PTP_NXT_PTP_NXT       BIT(0)
#define  VTSS_X_SYS_PTP_PTP_NXT_PTP_NXT(x)    VTSS_EXTRACT_BITFIELD(x,0,1)

#define VTSS_SYS_PTP_PTP_CFG                 VTSS_IOREG(VTSS_TO_SYS,0x1b1)
#define  VTSS_F_SYS_PTP_PTP_CFG_PTP_STAMP_WID(x)  VTSS_ENCODE_BITFIELD(x,2,6)
#define  VTSS_M_SYS_PTP_PTP_CFG_PTP_STAMP_WID     VTSS_ENCODE_BITMASK(2,6)
#define  VTSS_X_SYS_PTP_PTP_CFG_PTP_STAMP_WID(x)  VTSS_EXTRACT_BITFIELD(x,2,6)
#define  VTSS_F_SYS_PTP_PTP_CFG_PTP_CF_ROLL_MODE(x)  VTSS_ENCODE_BITFIELD(x,0,2)
#define  VTSS_M_SYS_PTP_PTP_CFG_PTP_CF_ROLL_MODE     VTSS_ENCODE_BITMASK(0,2)
#define  VTSS_X_SYS_PTP_PTP_CFG_PTP_CF_ROLL_MODE(x)  VTSS_EXTRACT_BITFIELD(x,0,2)


#endif /* _VTSS_OCELOT_REGS_SYS_H_ */
